# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
pkg_install_group:
  pkgs_common: true
  pkgs_extras: true
  pkgs_gui: true
  pkgs_server: false
  pkgs_software_development: true
  pkgs_software_libs: true

# Domain Options
pkg_install_top_level_domain: "com"
pkg_install_second_level_domain: "jcook3701"
pkg_install_domain_name: "{{ pkg_install_second_level_domain }}.{{ pkg_install_top_level_domain }}"
