# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Server backup preparation tasks
  tags: [never, server]
  block:
    - name: Include server variable files
      ansible.builtin.include_vars:
        file: nas.yml

- name: Workstation backup preparation tasks
  tags: [never, workstation]
  block:
    - name: Include workstation variable files
      ansible.builtin.include_vars:
        file: workstations.yml
