# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
cron_jobs_conf:
  role: update
  hosts: workstations

  scripts: "/update/update-workstations.yml"

  hour: 4
  minute: 30
