# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Import Server Package Variables
  ansible.builtin.include_vars: pkgs-server.yml

- name: Bind9 (DNS) Install
  ansible.builtin.include_tasks: bind9/bind9-install.yml
  when: pkgs_server.install.bind9

- name: DHCPD (DHCP) Install
  ansible.builtin.include_tasks: dhcpd/dhcpd-install.yml
  when: pkgs_server.install.dhcpd

- name: Firewalld Install
  ansible.builtin.include_tasks: firewalld/firewalld-install.yml
  when: pkgs_server.install.firewalld

- name: Mdadm (Raid) Install
  ansible.builtin.include_tasks: mdadm/mdadm-install.yml
  when: pkgs_server.install.mdadm

- name: OpenLdap (LDAP) Install
  ansible.builtin.include_tasks: openldap/openldap-install.yml
  when: pkgs_server.install.openldap

- name: Samba Install
  ansible.builtin.include_tasks: samba/samba-install.yml
  when: pkgs_server.install.samba

- name: VSFTP (FTP) Install
  ansible.builtin.include_tasks: vsftp/vsftp-install.yml
  when: pkgs_server.install.vsftp

- name: Webmin Install
  ansible.builtin.include_tasks: webmin/debian-webmin.yml
  when: pkgs_server.install.webmin
