# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
ansible_ssh_private_key_file: /root/.ssh/id_rsa
rdiff_script_path: "/usr/local/bin/rdiff-backup-script.sh"

log_filename: "{{ inventory_hostname_short }}-backup.log"
log_dir_path: "/var/log/backup-logs"
log_file_path: "{{ log_dir_path }}/{{ log_filename }}"

flags: "-v5 --print-statistics --exclude-sockets --exclude-device-files --exclude-fifos"

# directories to include/exclude durring the rdiff-backup
include:
  ["/boot", "/etc", "/home", "/opt", "/root", "/srv", "/usr/local", "/var"]
exclude:
  [
    "/bin",
    "/lib",
    "/lib64",
    "/sbin",
    "/dev",
    "/lost+found",
    "/media",
    "/mnt",
    "/proc",
    "/run",
    "/sys",
    "/tmp",
    "/usr",
    "/var/log",
    "/var/run",
    "/var/cache",
    "/var/tmp",
    "**",
  ]
