# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
source_dir: "/"
source_path: "{{ source_dir }}"
dest_server: "stone"
dest_dir: "/backups/{{ inventory_hostname_short }}"
# dest_path: - Set in role task
