# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
backup_server: "modern-times"

backup_source_dir: "/"
backup_dest_dir: "/media/raid10/samba_shares/samba_backup_share/rdiff-backups/{{ inventory_hostname_short }}"
